const QueryConstant = {
    ISSUE_HISTORY_ACTION_CREATED:'created',
    ISSUE_HISTORY_ACTION_UPDATED:'updated',
    ISSUE_HISTORY_ACTION_REMOVED:'removed',
    COMMENT_HISTORY_ACTION_DELETED:'deleted',
    TIME_TRACKING_HISTORY_ACTION_LOGGED:'logged',
    TIME_TRACKING_HISTORY_ACTION_UPDATED:'updated',
    PARTICIPANT_TYPE_REPORTER :'reporter',
    PARTICIPANT_TYPE_ASSIGNEE :'assignee'
}

export default QueryConstant;
